### ISSUE TITLE
`nvidia` module refuses to unload

### ISSUE THREAD

**Issue by gardotd426** [keithpl/single-gpu-passthrough#1]
So, I used to have a working single-GPU passthrough setup with my RTX 3090, but I quit using it for about a year. When I came back to it, instead of trying to fix my configs and whatnot I decided to start over. 

Well, I followed all the same instructions and guides as before (and they say the same thing as yours), and for some reason the Nvidia module refuses to unload. Have you ever seen anything like this?

Like, when I try to boot the VM, the GUI session ends, but the VM never boots up. When I SSH into the machine, I just see an `Input/output error` when I run `sudo systemctl status libvirtd`. When I did some more intensive troubleshooting, I realized that the `nvidia` module refuses to unload, even if `sddm` is stopped completely. No other modules are using it, but it says that it's in use. 

Do you have any ideas?

**Comment by keithpl** [comment]
Have you taken a peek at what processes are running? For me this happened a lot with alacritty, so much so I had to add a case for it in my libvirt hook.

Have you also tried unloading `nvidia*` yourself with either `modprobe -r` or `rmmod -f`?

**Comment by keithpl** [comment]
@gardotd426 did you figure out the issue?

**Comment by gardotd426** [comment]
Sorry, I didn't see your first reply in my email notifications. 

So, no I haven't figured it out, and I can't even unload the `nvidia` module manually from a TTY with EVERYTHING shut down. 

As in: I can boot my machine, I come to the SDDM login, I hit CTRL+ALT+F2 to go to a TTY, I log in, kill sddm with `sudo systemctl stop sddm.service`, then start unloading modules. 

I have to unload them in a specific order, nvidia-uvm then nvidia-drm then nvidia-modeset, but then I can't unload nvidia. 

I run `lsmod | grep nvidia` and it shows that no other modules are depending on it, `ps -ef | grep -E "nv|gpu" shows no processes with "nv" or "gpu" anywhere in the command are currently running, `sudo journalctl -b 0 | grep -i -e nvidia -i -e gpu` shows nothing useful.

Like, even `rmmod -f` and `modprobe -rf` don't work. It will NOT unload.

**Comment by keithpl** [comment]
Are you unbinding the efi framebuffer and vt consoles before attempting to unload? I would guess not since you're still in a getty trying all of this. I have two functions for this in my libvirt hook: `vtcon_binding()` and `efifb_binding()`.

I would suggest unsuring you're unbinding both before unloading the module, try either via the hook or remotely with ssh since your getty will die.

**Comment by gardotd426** [comment]
Oh I am. 

Sorry I forgot to mention that, yeah the first time I tried my getty died, but I have Termux on my phone so I just sshed in and tried to finish, and then when it didn't work I rebooted and tried the whole thing from my phone via SSH. 

No dice. But yeah, my script already unbinds the consoles and framebuffer. I THOUGHT that might be it when I first realized I wasn't doing it manually, but then I tried and sure enough, no dice.

**Comment by keithpl** [comment]
Have you looked at what processes might be utilizing the `nvidia` device? For instance: `sudo lsof /dev/nvidia0`

**Comment by gardotd426** [comment]
Holy shit that's a great idea, I've been wracking my brain to think of a
way I could search for processes using the GPU, but I completely forgot
about lsof. I'll try it out here when I'm done compiling this new kernel
and I'll let you know.

**Comment by keithpl** [comment]
@gardotd426 any progress?

**Comment by gardotd426** [comment]
Dude I'm so annoyed right now. I posted to the Nvidia developer forum this
morning, but I haven't gotten a response yet.

lsof /dev/nvidia0 has exactly zero output once sddm is killed. I even ran:

for i in $(find /usr/lib/ | grep nvidia); do lsof $i; done

And no output.

Obviously it gives a ton of output when any display server is running so
the command obviously is working though.

I have literally NO idea what could possibly be preventing the module from
unloading. I'm thinking about creating a small Endeavour or Garuda or even
Vanilla Arch install on a second partition with NO configuration other than
a display manager and DE and the NV drivers installed and see if it still
won't let me unload. If they won't unload, then something's broken in the
drivers. But if they do, then it's something in my system configuration.

**Comment by keithpl** [comment]
Have you tried `nvidia-open` instead of `nvidia` on arch? I've been running `nvidia-open` ever since ibt was enabled in the kernel, works great.

**Comment by gardotd426** [comment]
Last I heard (which was relatively recently) the open drivers don't support
a few things that I have to have. I'll look into trying though.

My next move if no one replies on the developer forums (they usually reply
right away) is to email ***@***.*** and then if that doesn't
work, I'll ping one of the Nvidia devs in the Linux Gaming Dev discord, but
I'd rather not have to do that because I know it's annoying when they get
pinged all the time.

**Comment by keithpl** [comment]
@gardotd426 did you ever resolve the issue?

**Comment by gardotd426** [comment]
I am completely flabbergasted. NV never responded to the email. I'm gonna
do a fresh install on a second partition to 100% confirm it's not some
system configuration error.
